### PR TITLE
updated S3 reference for SigV4 Compat

### PR DESCRIPTION
**Pull request by tbulding**
*Issue #, if available:*

updated S3 references for SigV4 Compat.
This is the same change I did for the rdgateway.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by avattathil** [comment]
@tbulding take a look at this line https://github.com/avattathil/cfn-authenticated-s3-example/blob/master/templates/authenticated-s3.template.yaml#L181

i have tested in extensively. But we should consider something more dynamic that. We may need a Mappings and Conditional to handle all regions/partitions

**Comment by avattathil** [comment]
_To add more context here:_
**the issue**: cfn-init does follow the s3 redirects, so we have to make calls with a fully qualified region based url. This means that you also need to have s3 staging in every support region for the given template. 

@TODOS
- We need to make update to taskcat to facilitate staging in multiple regions
- We need to stage quickstart template in all regions as well (deploy stage in out CI will need to upated)

 so we need to add something like to taskcat -> _f"{prefix}-{hashed_account_id}-{region_obj.name}_
and update the taskcat_autobucket function to return the appropriate bucket' .taskcat will create the bucket if it does not exist (so on first invocation) 

for taskcat staging:
`bucket = taskcat-3652e2f352e2-us-west-1` 

for quickstart prod staging : (we update the deploy code to stage to the following)
`aws-quickstart-us-west-1`

**Comment by mkamthe-xl** [comment]
If we take linux-bastion.template from tbulding/quickstart-linux-bastion:master, it works in us-east-1 region. We tried modifying https://github.com/tbulding/quickstart-linux-bastion/blob/master/templates/linux-bastion.template#L559 with s3.ap-south-1. Also tried with !Sub 's3.${AWS::Region}'. However we are unable to deploy bastion host in ap-south-1.

**Comment by tonynv** [comment]
Closing addressed in 977795280a12ca1f430b5dc3ccac8d9592ce261c

**Pull request closed without merging**
